### ISSUE TITLE
SMI Conformance Testing Support

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#122]
**Enhancement Description**
Linkerd is SMI compatible. Its compatibility needs to be verified against the standard suite of compliance tests.

**Comment by leecalcote** [comment]
Duplicative of #77

**Comment by dhruv0000** [comment]
The recent effort update the SMI results in [layer5 site](https://layer5.io/service-mesh-landscape#smi), covered the effort of checking the compliance of `linkerd v2.10.0` against the standard test suite.

**Comment by leecalcote** [comment]
Ok, good. Safe to close this issue, I think.
