### ISSUE TITLE
[Lifecycle] Unable to provision Linkerd control plane

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#127]
**Description**
The Linkerd adapter has new logic checks for objects. Provisioning Linkerd and providing `linkerd` as the namespace, the following error is returned:

**Screenshots**
<img width="987" alt="Screen Shot 2020-10-11 at 9 08 33 PM" src="https://user-images.githubusercontent.com/7570704/95701421-2af9f880-0c0f-11eb-8dda-08c619a5f54a.png">

**Comment by kumarabd** [comment]
<img width="1466" alt="Screenshot 2020-10-12 at 12 12 45 PM" src="https://user-images.githubusercontent.com/10404724/95713487-3fc4a380-0c84-11eb-8427-8f71db3983eb.png">

Im unable to replicate @leecalcote. I ran install linkerd in `linkerd` namespace and I've got them all installed.

**Comment by leecalcote** [comment]
Let’s get on a call...
