### ISSUE TITLE
Displace istio reference in ci workflow with linkerd

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#181]
**Description**
The static analysis check in this repo [is failing,](https://github.com/layer5io/meshery-linkerd/runs/2141602946?check_suite_focus=true#step:4:21) because it is referencing an istio file - https://github.com/layer5io/meshery-linkerd/search?q=istio

**Comment by Aisuko** [comment]
I saw there's a `.golangci.yaml` in our project, why we add these CI steps. If I remember right,  all our adapters repo all transferred `CI` to `golangci-lint`, right?

**Comment by Aisuko** [comment]
We can fix the CI configuration at first.

**Comment by Aisuko** [comment]
@ramrodo If I remember right, we already made a choice on `golangci-lint` right? Sorry I don't remember which docs record this

**Comment by ramrodo** [comment]
@Aisuko I think that decision was made before I join the project. But it seems it's true, in `meshery-consul` we use `golangci-lint`. So, I think we can change it to use the later.
