### ISSUE TITLE
Builds: Static and Error checking of Go code

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#32]
**Enhancement Description**
In order to facilitate coding best practices, this adapter's code should have static analysis and error checking run as part of its build process.

**Chore Description**
Using the meshery-istio adapter's Actions workflow as an example, enable [Static and Error checks](https://github.com/layer5io/meshery-istio/blob/master/.github/workflows/ci.yml#L26-L51) in this repository's [CI.yml workflow](../blob/master/.github/workflows/ci.yml).

**Comment by leecalcote** [comment]
@nupur-thakur, as a way of familiarizing with the project and expanding your Go skills, would you like to give this issue a try?

**Comment by nupur-thakur** [comment]
@leecalcote Yes. I will try to do this and let you kniw if I get stuck somewhere.

**Comment by nupur-thakur** [comment]
Hello @leecalcote I was trying to understand that what exactly I have to do after figuring it out when i checked the ci.yml file of meshery-linkerd I realised that the code for static error checking of Go Code is already there but it has been commented out by somebody.
So do I just need to uncomment and understand the code or I have to find the errors in it if it were there?

**Comment by nupur-thakur** [comment]
@gunjanmimo as you have referenced this issue just a few minutes ago if you could guide me, it will be a great help.

**Comment by girishranganathan** [comment]
@nupur-thakur yes you are right. You have to uncomment and then go around fixing the errors pointed out by the checks. Feel free to reach out to me if you have any questions.

**Comment by kushthedude** [comment]
Hey, @nupur-thakur Still working on this issue? If not, may I give it a shot

**Comment by nupur-thakur** [comment]
@kushthedude I am no longer working on this issue as a PR have already merged regarding this Issue by @gunjanmimo

**Comment by kushthedude** [comment]
@leecalcote This issue can be closed then.

**Comment by gunjanmimo** [comment]
there are some more errors, so I need some time. so we should keep this pr open @kushthedude

**Comment by antweiss** [comment]
@gunjanmimo I believe I fixed all the warnings and errors in my latest PR. Please try to rebase on the latest master.
