### ISSUE TITLE
Add 'linkerd check' to verify linkerd installation 

### ISSUE THREAD

**Issue by antweiss** [layer5io/meshery-linkerd#38]
**Enhancement Description**
Currently there's only a check pre-installation.
The success isn't verified.
Meshery notifies on installation success while the images for linkerd are still being initialized.
I think we should wait until 'linkerd check' returns full success.

**Related Challenges**
The use may have to wait a bit longer until Linkerd installation is confirmed. But I think this is better then notifying of success without actually verifying it.

-

**Comment by Aisuko** [comment]
Close by PR https://github.com/layer5io/meshery-linkerd/pull/61
