### ISSUE TITLE
Add issue templates: bug and enhancement

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#5]
Create two issue templates in the *meshery-linkerd* repo by copying the meshery repo's [issue templates](https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE).

**Comment by gunjanmimo** [comment]
sir i did completed properly

**Comment by leecalcote** [comment]
Fixed by #6.

**Comment by leecalcote** [comment]
Thank you, @gunjanmimo.
