### ISSUE TITLE
[Install] Linkerd installation failure

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#70]
**Description**
```
received error while attempting to prepare install yaml: time="2020-07-05T19:54:31Z" level=error msg="could not set namespace from kubectl context: ensure a valid KUBECONFIG path has been set"
```

**Environment**
Meshery Client Version: 0.3.18
Meshery Server Version: v0.4.0-beta.1

**Comment by Aisuko** [comment]
OK, the issue on my schedule now.

**Comment by leecalcote** [comment]
Thank you, @Aisuko

**Comment by Aisuko** [comment]
> Thank you, @Aisuko

@leecalcote You are welcome, sir. I need more time as you know that my work hours.😱😱

**Comment by Aisuko** [comment]
Fixed by PR https://github.com/layer5io/meshery-linkerd/pull/99
