### ISSUE TITLE
Add releasedrafter workflow and configuration files to this repo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#81]
**Current Situation**
The [ReleaseDrafter](https://github.com/marketplace/actions/release-drafter) utility (GitHub Action) is not configured in this repository.

**Desired Situation**
- Releasedrafter should be configured to execute whenever a PR is merged to master in this repo.

**Implementation**
- Copy the [releasedrafter config](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml) and the [releasedrafter workflow](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml) file from the `meshery` repo and place in the `.github` folder here.

**Comment by Aisuko** [comment]
@PmcFizz As we discussed, would you like to contribute this one?

**Comment by PmcFizz** [comment]
Yes, I  will create a workflow for this project.

**Comment by leecalcote** [comment]
Excellent! The workflow and configuration linked above can be copied verbatim. 👍

**Comment by PluckyPrecious** [comment]
A PR was merged to this effect 9days ago. So I'm closing this issue now.
