### ISSUE TITLE
Add Layer5 Welcome bot to the Meshery adapter for Linkerd repository

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-linkerd#86]
**Current Situation**
A welcome bot has been configured to usher in contributors new to this project. Configuration of this welcome bot is missing from the `meshery-consul` repository, however.

**Desired Situation**
The [config.yml](https://github.com/layer5io/meshery/blob/master/.github/config.yml) and the [`welcome` folder](https://github.com/layer5io/meshery/tree/master/.github/welcome) along with the [image](https://github.com/layer5io/meshery/blob/master/.github/welcome/Layer5-celebration.png) inside of it should be copied and placed into the [.github folder in this repository](https://github.com/layer5io/meshery-consul/tree/master/.github).

**Comment by tonyanant** [comment]
Hello, can I work on this issue?

**Comment by PluckyPrecious** [comment]
Yes you can @tonyanant.💪🏽

**Comment by tonyanant** [comment]
I just performed a [pull request](https://github.com/layer5io/meshery-consul/pull/79) regarding this issue. I hope I did everything correctly regarding the pull request and if not I'd love to get some feedback on what I did wrong. Thank you.

**Comment by leecalcote** [comment]
@tonyanant you did swell job. I actually messed up here. I meant to request that the config.yml file be created in _this_ repository - the Linkerd repository. Will you consider filing another PR against this repo?

**Comment by tonyanant** [comment]
Sure, but what exactly would you like me to do? I am not sure I understand.

**Comment by leecalcote** [comment]
@tonyanant the same thing that you did in the Meshery-consul repo, but done in this repo (Meshery-linkerd).

**Comment by leecalcote** [comment]
@tonyanant feel free to ping me in Slack, if this still doesn't quite make sense. (http://slack.layer5.io)

**Comment by PluckyPrecious** [comment]
Hi, @tonyanant I think this sums up what @leecalcote is saying. Hope you're clear. 😃 

**Current Behavior**
 A welcome bot has been configured to usher in contributors new to this project. Configuration of this welcome bot is missing from the `meshery-linkered` repository.


**Desired Behavior**
 The [config.yml](https://github.com/layer5io/meshery/blob/master/.github/config.yml) and the [welcome folder](https://github.com/layer5io/meshery/tree/master/.github/welcome) along with the [image](https://github.com/layer5io/meshery/blob/master/.github/welcome/Layer5-celebration.png) inside of it should be copied and placed into the [.github folder in this repository](https://github.com/layer5io/meshery-linkerd/tree/master/.github).

**Comment by tonyanant** [comment]
Ok, I understand what needs to be done and I'll get to it. Thank you! 👍

**Comment by tonyanant** [comment]
I completed the task and just made the pull request. I hope everything works fine. :)

**Comment by PluckyPrecious** [comment]
I doubt it's from your end, @leecalcote will resolve it. Welldon. 🥳

**Comment by tonyanant** [comment]
Thank you! You've helped me greatly on performing my first contribution and in starting to learn how github and open source works! Thanks for everything and if there are any other beginner issues I'd be glad to contribute more!  :D

**Comment by leecalcote** [comment]
Very cool, @tonyanant. 😄 There's more where that came from. Have you joined the community Slack? If not, here you go - http://slack.layer5.io. Be sure to have a look at [this doc](https://docs.google.com/document/d/1tpg2sLxirozNt3Ofr3GdM002f9rExp74EqrsGZBU710/edit?usp=sharing).

**Comment by Ruth-ikegah** [comment]
Nice work @tonyanant
